### ISSUE TITLE
Organization not visible on profile

### ISSUE THREAD

**Issue by adevade** [Astrotomic/opendor.me#95]
I'm a public member of @035media org which has some public repos, but they are not showing up on my profile. Anything I'm doing wrong, or some bug?

**Comment by Gummibeer** [comment]
Hey, I see 3 repos and all of them are forked or archived.
As forked repos are 99% not the work or aren't maintained by the forker we ignore them by default.
I haven't checked them in detail - one has a changed name, so possibily the worked was only a template?

**Comment by Gummibeer** [comment]
Have checked, organization is indexed, you are a member of but the two public repos are hidden because of fork.
You should see the organization if you click "view contributions" in the user drop-down. In that view all organizations are listed in the left sidebar.

As it's about open-source we hide organizations without visible repositories.

**Comment by adevade** [comment]
I understand! Thank you for your reply and time! 🙏
